### ISSUE TITLE
我发现的一些bug

### ISSUE THREAD

**Issue by wh-wang132** [Silver-Ray/AD9959#1]
1.函数Phase2Word中,uint16_t Temp = (uint16_t)(0.02197265625 * Phase)实际应为uint16_t Temp = (uint16_t) ((double) Phase * 45.511111111),因为16384/360≈45.1111
2.ad9959.h中未声明函数Phase2Word
3.函数WriteData_AD9959中,IO_Update()语句会导致用户连续对多个值操作时寄存器被异步刷新,应将WriteData_AD9959中的,IO_Update()注释并在用户连续操作之后放入IO_Update()以一次性刷新所有要改变的寄存器

**Comment by Silver-Ray** [comment]
电赛前夕，在写了ASK和FSK的函数实现并验证后就推上main branch, `Phase2Word()`为实现PSK函数时添加的，同时修改了`Write_Phase()`函数而未做验证，`IO_Update()`确实会对操作有一定影响。已修复，感谢指正。
